export {ReactComponent as ElectronicIcon} from "./resources/synth.svg"
export {ReactComponent as MetalIcon} from "./resources/metal-guitar.svg"
export {ReactComponent as LatinIcon} from "./resources/maracas.svg"
export {ReactComponent as JazzIcon} from "./resources/trumpet.svg"
export {ReactComponent as RockIcon} from "./resources/electric-guitar.svg"
export {ReactComponent as ClassicalIcon} from "./resources/harp.svg"
export {ReactComponent as FolkIcon} from "./resources/acoustic-guitar.svg"
export {ReactComponent as DjIcon} from "./resources/dj.svg"
